name: 'CI Telegram Sender (Forced)'
description: 'Send messages and files to Telegram chat and Thread in Chat'

branding:
  icon: 'alert-triangle'
  color: 'green'

runs:
  using: 'docker'
  image: 'docker://ormgair/tg_sender:latest'
